#! /usr/bin/env python3

import sys
import code
#import elfesteem.elf
import readline
import rlcompleter
import argparse

from elfesteem import elf_init


def main():
    
    parser = argparse.ArgumentParser()
    parser.add_argument("infile")

    args = parser.parse_args()

    # prepare locals and binding for interactive session
    readline.parse_and_bind("tab: complete")

    
    elf = elf_init.ELF(open(args.infile, 'rb').read())
    
    code.interact(local=locals())
    

if __name__ == "__main__":
    main()
